// Auto-generated by scripts/generate-project-media.mjs

export type GeneratedProjectMedia = {
  src: string;
  alt: string;
  label: string;
  kind: "photo" | "drawing" | "pdf-preview";
};

export type GeneratedProject = {
  slug: string;
  title: string;
  category: string;
  location: string;
  status: string;
  description: string;
  scope: string[];
  overview: string;
  priorities: string[];
  media: GeneratedProjectMedia[];
};

export const generatedProjects: GeneratedProject[] = [
  {
    "slug": "balram-chabada-panhala",
    "title": "Balram Chabada Panhala",
    "category": "Residential Construction",
    "location": "Panhala",
    "status": "Completed",
    "description": "Balram Chabada Panhala is a residential construction project by JVS Enterprises in Panhala, executed with practical site supervision and durable construction quality.",
    "scope": [
      "Residential Construction",
      "RCC & Structural Work",
      "Finishing",
      "Site Coordination"
    ],
    "overview": "Balram Chabada Panhala is presented through real project imagery, drawings, and on-site progress records maintained by JVS Enterprises.",
    "priorities": [
      "Disciplined residential execution",
      "Structural reliability",
      "Finishing and usability focus",
      "Site-level coordination"
    ],
    "media": [
      {
        "src": "/images/projects/balram-chabada-panhala/balram-chabada-panhala--photo-01-completed-1.webp",
        "alt": "Balram Chabada Panhala - Completed 1",
        "label": "Completed 1",
        "kind": "photo"
      },
      {
        "src": "/images/projects/balram-chabada-panhala/balram-chabada-panhala--photo-02-completed-2.webp",
        "alt": "Balram Chabada Panhala - Completed 2",
        "label": "Completed 2",
        "kind": "photo"
      },
      {
        "src": "/images/projects/balram-chabada-panhala/balram-chabada-panhala--photo-03-20190525-121135.webp",
        "alt": "Balram Chabada Panhala - 20190525 121135",
        "label": "20190525 121135",
        "kind": "photo"
      },
      {
        "src": "/images/projects/balram-chabada-panhala/balram-chabada-panhala--photo-04-20200122-174137.webp",
        "alt": "Balram Chabada Panhala - 20200122 174137",
        "label": "20200122 174137",
        "kind": "photo"
      },
      {
        "src": "/images/projects/balram-chabada-panhala/balram-chabada-panhala--photo-05-20200122-174204.webp",
        "alt": "Balram Chabada Panhala - 20200122 174204",
        "label": "20200122 174204",
        "kind": "photo"
      },
      {
        "src": "/images/projects/balram-chabada-panhala/balram-chabada-panhala--photo-06-20200206-131528.webp",
        "alt": "Balram Chabada Panhala - 20200206 131528",
        "label": "20200206 131528",
        "kind": "photo"
      },
      {
        "src": "/images/projects/balram-chabada-panhala/balram-chabada-panhala--photo-07-20200206-132406.webp",
        "alt": "Balram Chabada Panhala - 20200206 132406",
        "label": "20200206 132406",
        "kind": "photo"
      },
      {
        "src": "/images/projects/balram-chabada-panhala/balram-chabada-panhala--photo-08-20200905-101819.webp",
        "alt": "Balram Chabada Panhala - 20200905 101819",
        "label": "20200905 101819",
        "kind": "photo"
      },
      {
        "src": "/images/projects/balram-chabada-panhala/balram-chabada-panhala--photo-09-20201205-141126.webp",
        "alt": "Balram Chabada Panhala - 20201205 141126",
        "label": "20201205 141126",
        "kind": "photo"
      },
      {
        "src": "/images/projects/balram-chabada-panhala/balram-chabada-panhala--photo-10-20201205-152834.webp",
        "alt": "Balram Chabada Panhala - 20201205 152834",
        "label": "20201205 152834",
        "kind": "photo"
      },
      {
        "src": "/images/projects/balram-chabada-panhala/balram-chabada-panhala--photo-11-20201205-152837.webp",
        "alt": "Balram Chabada Panhala - 20201205 152837",
        "label": "20201205 152837",
        "kind": "photo"
      },
      {
        "src": "/images/projects/balram-chabada-panhala/balram-chabada-panhala--photo-12-20201228-175808.webp",
        "alt": "Balram Chabada Panhala - 20201228 175808",
        "label": "20201228 175808",
        "kind": "photo"
      },
      {
        "src": "/images/projects/balram-chabada-panhala/balram-chabada-panhala--photo-13-20201228-175924.webp",
        "alt": "Balram Chabada Panhala - 20201228 175924",
        "label": "20201228 175924",
        "kind": "photo"
      },
      {
        "src": "/images/projects/balram-chabada-panhala/balram-chabada-panhala--photo-14-20201229-135627.webp",
        "alt": "Balram Chabada Panhala - 20201229 135627",
        "label": "20201229 135627",
        "kind": "photo"
      },
      {
        "src": "/images/projects/balram-chabada-panhala/balram-chabada-panhala--photo-15-20210128-150217.webp",
        "alt": "Balram Chabada Panhala - 20210128 150217",
        "label": "20210128 150217",
        "kind": "photo"
      },
      {
        "src": "/images/projects/balram-chabada-panhala/balram-chabada-panhala--photo-16-img-20201224-wa0045.webp",
        "alt": "Balram Chabada Panhala - Img 20201224 Wa0045",
        "label": "Img 20201224 Wa0045",
        "kind": "photo"
      },
      {
        "src": "/images/projects/balram-chabada-panhala/balram-chabada-panhala--photo-17-img-20210102-wa0020.webp",
        "alt": "Balram Chabada Panhala - Img 20210102 Wa0020",
        "label": "Img 20210102 Wa0020",
        "kind": "photo"
      },
      {
        "src": "/images/projects/balram-chabada-panhala/balram-chabada-panhala--photo-18-img-20210102-wa0021.webp",
        "alt": "Balram Chabada Panhala - Img 20210102 Wa0021",
        "label": "Img 20210102 Wa0021",
        "kind": "photo"
      },
      {
        "src": "/images/projects/balram-chabada-panhala/balram-chabada-panhala--drawing-19-drawing-1.webp",
        "alt": "Balram Chabada Panhala - Drawing 1",
        "label": "Drawing 1",
        "kind": "drawing"
      }
    ]
  },
  {
    "slug": "dr-sanjay-d-patil-luxurious-farmhouse-panhala",
    "title": "Dr. Sanjay D Patil Luxurious Farmhouse",
    "category": "Farmhouse Construction",
    "location": "Panhala",
    "status": "Completed",
    "description": "Farmhouse construction work by JVS Enterprises in Panhala, covering structural execution, external development, and long-term performance.",
    "scope": [
      "Farmhouse Construction",
      "RCC & Structural Work",
      "Finishing",
      "External Development"
    ],
    "overview": "Dr. Sanjay D Patil Luxurious Farmhouse is presented through real project imagery, drawings, and on-site progress records maintained by JVS Enterprises.",
    "priorities": [
      "Terrain-aware execution",
      "Drainage and external usability",
      "Long-term weather resilience",
      "Coordinated finishing quality"
    ],
    "media": [
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-01-complete-1.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Complete 1",
        "label": "Complete 1",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-02-20201227-125931.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - 20201227 125931",
        "label": "20201227 125931",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-03-20201228-123440.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - 20201228 123440",
        "label": "20201228 123440",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-04-20201228-123446.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - 20201228 123446",
        "label": "20201228 123446",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-05-20210710-160823.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - 20210710 160823",
        "label": "20210710 160823",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-06-bedroom-1.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Bedroom 1",
        "label": "Bedroom 1",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-07-bedroom.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Bedroom",
        "label": "Bedroom",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-08-firespace.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Firespace",
        "label": "Firespace",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-09-gate.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Gate",
        "label": "Gate",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-10-hall.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Hall",
        "label": "Hall",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-11-img-20210601-wa0012.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Img 20210601 Wa0012",
        "label": "Img 20210601 Wa0012",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-12-img-20210602-wa0012.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Img 20210602 Wa0012",
        "label": "Img 20210602 Wa0012",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-13-img-20210604-wa0014.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Img 20210604 Wa0014",
        "label": "Img 20210604 Wa0014",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-14-img-20210604-wa0016.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Img 20210604 Wa0016",
        "label": "Img 20210604 Wa0016",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-15-img-20210610-wa0060.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Img 20210610 Wa0060",
        "label": "Img 20210610 Wa0060",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-16-img-20210620-wa0031.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Img 20210620 Wa0031",
        "label": "Img 20210620 Wa0031",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-17-img-20210626-wa0059.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Img 20210626 Wa0059",
        "label": "Img 20210626 Wa0059",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-18-img-20210626-wa0062.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Img 20210626 Wa0062",
        "label": "Img 20210626 Wa0062",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-19-img-20210630-wa0040.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Img 20210630 Wa0040",
        "label": "Img 20210630 Wa0040",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-20-img-20210630-wa0041.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Img 20210630 Wa0041",
        "label": "Img 20210630 Wa0041",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-21-img-20210630-wa0042.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Img 20210630 Wa0042",
        "label": "Img 20210630 Wa0042",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-22-img-20210630-wa0043.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Img 20210630 Wa0043",
        "label": "Img 20210630 Wa0043",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-23-img-20210630-wa0044.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Img 20210630 Wa0044",
        "label": "Img 20210630 Wa0044",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-24-img-20210630-wa0045.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Img 20210630 Wa0045",
        "label": "Img 20210630 Wa0045",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-25-img-20210630-wa0046.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Img 20210630 Wa0046",
        "label": "Img 20210630 Wa0046",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-26-img-20210630-wa0047.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Img 20210630 Wa0047",
        "label": "Img 20210630 Wa0047",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-27-img-20210630-wa0052.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Img 20210630 Wa0052",
        "label": "Img 20210630 Wa0052",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-28-img-20210630-wa0056.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Img 20210630 Wa0056",
        "label": "Img 20210630 Wa0056",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-29-img-20210630-wa0057.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Img 20210630 Wa0057",
        "label": "Img 20210630 Wa0057",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-30-img-20210709-wa0033.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Img 20210709 Wa0033",
        "label": "Img 20210709 Wa0033",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-31-img-20210710-wa0034.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Img 20210710 Wa0034",
        "label": "Img 20210710 Wa0034",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-32-img-20210710-wa0036.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Img 20210710 Wa0036",
        "label": "Img 20210710 Wa0036",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-33-img-20210711-wa0020.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Img 20210711 Wa0020",
        "label": "Img 20210711 Wa0020",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-34-img-20210711-wa0021.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Img 20210711 Wa0021",
        "label": "Img 20210711 Wa0021",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-35-img-20210711-wa0022.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Img 20210711 Wa0022",
        "label": "Img 20210711 Wa0022",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-36-img-20210711-wa0023.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Img 20210711 Wa0023",
        "label": "Img 20210711 Wa0023",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-37-img-20210711-wa0024.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Img 20210711 Wa0024",
        "label": "Img 20210711 Wa0024",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-38-img-20210711-wa0026.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Img 20210711 Wa0026",
        "label": "Img 20210711 Wa0026",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-39-img-20210711-wa0028.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Img 20210711 Wa0028",
        "label": "Img 20210711 Wa0028",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-40-img-20210711-wa0030.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Img 20210711 Wa0030",
        "label": "Img 20210711 Wa0030",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-41-img-20210711-wa0032.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Img 20210711 Wa0032",
        "label": "Img 20210711 Wa0032",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-42-img-20210711-wa0033.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Img 20210711 Wa0033",
        "label": "Img 20210711 Wa0033",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-43-interior-1.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Interior 1",
        "label": "Interior 1",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-44-interior-2.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Interior 2",
        "label": "Interior 2",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-45-interior-3.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Interior 3",
        "label": "Interior 3",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-46-interior-4.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Interior 4",
        "label": "Interior 4",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-47-interior-5.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Interior 5",
        "label": "Interior 5",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-48-interior-6.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Interior 6",
        "label": "Interior 6",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-49-lawn-2.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Lawn 2",
        "label": "Lawn 2",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-50-lawn.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Lawn",
        "label": "Lawn",
        "kind": "photo"
      },
      {
        "src": "/images/projects/dr-sanjay-d-patil-luxurious-farmhouse-panhala/dr-sanjay-d-patil-luxurious-farmhouse-panhala--photo-51-parking.webp",
        "alt": "Dr. Sanjay D Patil Luxurious Farmhouse - Parking",
        "label": "Parking",
        "kind": "photo"
      }
    ]
  },
  {
    "slug": "ingle-panhala-guest-house-luxury",
    "title": "Ingle Panhala Guest House Luxury",
    "category": "Residential Construction",
    "location": "Panhala",
    "status": "Completed",
    "description": "Ingle Panhala Guest House Luxury is a residential construction project by JVS Enterprises in Panhala, executed with practical site supervision and durable construction quality.",
    "scope": [
      "Residential Construction",
      "RCC & Structural Work",
      "Finishing",
      "Site Coordination"
    ],
    "overview": "Ingle Panhala Guest House Luxury is presented through real project imagery, drawings, and on-site progress records maintained by JVS Enterprises.",
    "priorities": [
      "Disciplined residential execution",
      "Structural reliability",
      "Finishing and usability focus",
      "Site-level coordination"
    ],
    "media": [
      {
        "src": "/images/projects/ingle-panhala-guest-house-luxury/ingle-panhala-guest-house-luxury--photo-01-completed-1.webp",
        "alt": "Ingle Panhala Guest House Luxury - Completed 1",
        "label": "Completed 1",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ingle-panhala-guest-house-luxury/ingle-panhala-guest-house-luxury--photo-02-completed-2.webp",
        "alt": "Ingle Panhala Guest House Luxury - Completed 2",
        "label": "Completed 2",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ingle-panhala-guest-house-luxury/ingle-panhala-guest-house-luxury--photo-03-20190422-130208.webp",
        "alt": "Ingle Panhala Guest House Luxury - 20190422 130208",
        "label": "20190422 130208",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ingle-panhala-guest-house-luxury/ingle-panhala-guest-house-luxury--photo-04-20190506-144808.webp",
        "alt": "Ingle Panhala Guest House Luxury - 20190506 144808",
        "label": "20190506 144808",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ingle-panhala-guest-house-luxury/ingle-panhala-guest-house-luxury--photo-05-20190508-180817.webp",
        "alt": "Ingle Panhala Guest House Luxury - 20190508 180817",
        "label": "20190508 180817",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ingle-panhala-guest-house-luxury/ingle-panhala-guest-house-luxury--photo-06-20190509-123659.webp",
        "alt": "Ingle Panhala Guest House Luxury - 20190509 123659",
        "label": "20190509 123659",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ingle-panhala-guest-house-luxury/ingle-panhala-guest-house-luxury--photo-07-20190510-131222.webp",
        "alt": "Ingle Panhala Guest House Luxury - 20190510 131222",
        "label": "20190510 131222",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ingle-panhala-guest-house-luxury/ingle-panhala-guest-house-luxury--photo-08-20190621-161959.webp",
        "alt": "Ingle Panhala Guest House Luxury - 20190621 161959",
        "label": "20190621 161959",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ingle-panhala-guest-house-luxury/ingle-panhala-guest-house-luxury--photo-09-20190720-171037.webp",
        "alt": "Ingle Panhala Guest House Luxury - 20190720 171037",
        "label": "20190720 171037",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ingle-panhala-guest-house-luxury/ingle-panhala-guest-house-luxury--photo-10-20191016-153404.webp",
        "alt": "Ingle Panhala Guest House Luxury - 20191016 153404",
        "label": "20191016 153404",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ingle-panhala-guest-house-luxury/ingle-panhala-guest-house-luxury--photo-11-20191201-154416.webp",
        "alt": "Ingle Panhala Guest House Luxury - 20191201 154416",
        "label": "20191201 154416",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ingle-panhala-guest-house-luxury/ingle-panhala-guest-house-luxury--photo-12-20191211-154626.webp",
        "alt": "Ingle Panhala Guest House Luxury - 20191211 154626",
        "label": "20191211 154626",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ingle-panhala-guest-house-luxury/ingle-panhala-guest-house-luxury--photo-13-20191211-154857.webp",
        "alt": "Ingle Panhala Guest House Luxury - 20191211 154857",
        "label": "20191211 154857",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ingle-panhala-guest-house-luxury/ingle-panhala-guest-house-luxury--photo-14-20200109-175505.webp",
        "alt": "Ingle Panhala Guest House Luxury - 20200109 175505",
        "label": "20200109 175505",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ingle-panhala-guest-house-luxury/ingle-panhala-guest-house-luxury--photo-15-20200109-175725.webp",
        "alt": "Ingle Panhala Guest House Luxury - 20200109 175725",
        "label": "20200109 175725",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ingle-panhala-guest-house-luxury/ingle-panhala-guest-house-luxury--photo-16-20200115-120926.webp",
        "alt": "Ingle Panhala Guest House Luxury - 20200115 120926",
        "label": "20200115 120926",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ingle-panhala-guest-house-luxury/ingle-panhala-guest-house-luxury--photo-17-20200124-140519.webp",
        "alt": "Ingle Panhala Guest House Luxury - 20200124 140519",
        "label": "20200124 140519",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ingle-panhala-guest-house-luxury/ingle-panhala-guest-house-luxury--photo-18-20200224-172750.webp",
        "alt": "Ingle Panhala Guest House Luxury - 20200224 172750",
        "label": "20200224 172750",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ingle-panhala-guest-house-luxury/ingle-panhala-guest-house-luxury--photo-19-20200525-172104.webp",
        "alt": "Ingle Panhala Guest House Luxury - 20200525 172104",
        "label": "20200525 172104",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ingle-panhala-guest-house-luxury/ingle-panhala-guest-house-luxury--photo-20-20200525-174932.webp",
        "alt": "Ingle Panhala Guest House Luxury - 20200525 174932",
        "label": "20200525 174932",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ingle-panhala-guest-house-luxury/ingle-panhala-guest-house-luxury--photo-21-20200525-190142.webp",
        "alt": "Ingle Panhala Guest House Luxury - 20200525 190142",
        "label": "20200525 190142",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ingle-panhala-guest-house-luxury/ingle-panhala-guest-house-luxury--photo-22-20200525-191146.webp",
        "alt": "Ingle Panhala Guest House Luxury - 20200525 191146",
        "label": "20200525 191146",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ingle-panhala-guest-house-luxury/ingle-panhala-guest-house-luxury--photo-23-20200525-191346.webp",
        "alt": "Ingle Panhala Guest House Luxury - 20200525 191346",
        "label": "20200525 191346",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ingle-panhala-guest-house-luxury/ingle-panhala-guest-house-luxury--photo-24-20200525-191349.webp",
        "alt": "Ingle Panhala Guest House Luxury - 20200525 191349",
        "label": "20200525 191349",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ingle-panhala-guest-house-luxury/ingle-panhala-guest-house-luxury--photo-25-20200525-192612.webp",
        "alt": "Ingle Panhala Guest House Luxury - 20200525 192612",
        "label": "20200525 192612",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ingle-panhala-guest-house-luxury/ingle-panhala-guest-house-luxury--pdf-preview-26-guest-house-brick-masonry-layout.webp",
        "alt": "Ingle Panhala Guest House Luxury - Guest House Brick Masonry Layout",
        "label": "Guest House Brick Masonry Layout",
        "kind": "pdf-preview"
      },
      {
        "src": "/images/projects/ingle-panhala-guest-house-luxury/ingle-panhala-guest-house-luxury--pdf-preview-27-guest-house-rubble-masonry-layout.webp",
        "alt": "Ingle Panhala Guest House Luxury - Guest House Rubble Masonry Layout",
        "label": "Guest House Rubble Masonry Layout",
        "kind": "pdf-preview"
      }
    ]
  },
  {
    "slug": "ishwer-sevani-residential-premium-farmhouse",
    "title": "Ishwer Sevani Residential Premium Farmhouse",
    "category": "Farmhouse Construction",
    "location": "Kolhapur Region",
    "status": "Completed",
    "description": "Farmhouse construction work by JVS Enterprises in Kolhapur Region, covering structural execution, external development, and long-term performance.",
    "scope": [
      "Farmhouse Construction",
      "RCC & Structural Work",
      "Finishing",
      "External Development"
    ],
    "overview": "Ishwer Sevani Residential Premium Farmhouse is presented through real project imagery, drawings, and on-site progress records maintained by JVS Enterprises.",
    "priorities": [
      "Terrain-aware execution",
      "Drainage and external usability",
      "Long-term weather resilience",
      "Coordinated finishing quality"
    ],
    "media": [
      {
        "src": "/images/projects/ishwer-sevani-residential-premium-farmhouse/ishwer-sevani-residential-premium-farmhouse--photo-01-complete-1.webp",
        "alt": "Ishwer Sevani Residential Premium Farmhouse - Complete 1",
        "label": "Complete 1",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ishwer-sevani-residential-premium-farmhouse/ishwer-sevani-residential-premium-farmhouse--photo-02-20211127-172524.webp",
        "alt": "Ishwer Sevani Residential Premium Farmhouse - 20211127 172524",
        "label": "20211127 172524",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ishwer-sevani-residential-premium-farmhouse/ishwer-sevani-residential-premium-farmhouse--photo-03-20211127-172526.webp",
        "alt": "Ishwer Sevani Residential Premium Farmhouse - 20211127 172526",
        "label": "20211127 172526",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ishwer-sevani-residential-premium-farmhouse/ishwer-sevani-residential-premium-farmhouse--photo-04-20211222-132206.webp",
        "alt": "Ishwer Sevani Residential Premium Farmhouse - 20211222 132206",
        "label": "20211222 132206",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ishwer-sevani-residential-premium-farmhouse/ishwer-sevani-residential-premium-farmhouse--photo-05-20220101-154727.webp",
        "alt": "Ishwer Sevani Residential Premium Farmhouse - 20220101 154727",
        "label": "20220101 154727",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ishwer-sevani-residential-premium-farmhouse/ishwer-sevani-residential-premium-farmhouse--photo-06-20220101-162214.webp",
        "alt": "Ishwer Sevani Residential Premium Farmhouse - 20220101 162214",
        "label": "20220101 162214",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ishwer-sevani-residential-premium-farmhouse/ishwer-sevani-residential-premium-farmhouse--photo-07-20220101-162233.webp",
        "alt": "Ishwer Sevani Residential Premium Farmhouse - 20220101 162233",
        "label": "20220101 162233",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ishwer-sevani-residential-premium-farmhouse/ishwer-sevani-residential-premium-farmhouse--photo-08-20220101-162242.webp",
        "alt": "Ishwer Sevani Residential Premium Farmhouse - 20220101 162242",
        "label": "20220101 162242",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ishwer-sevani-residential-premium-farmhouse/ishwer-sevani-residential-premium-farmhouse--photo-09-20220115-112947.webp",
        "alt": "Ishwer Sevani Residential Premium Farmhouse - 20220115 112947",
        "label": "20220115 112947",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ishwer-sevani-residential-premium-farmhouse/ishwer-sevani-residential-premium-farmhouse--photo-10-20220219-125457.webp",
        "alt": "Ishwer Sevani Residential Premium Farmhouse - 20220219 125457",
        "label": "20220219 125457",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ishwer-sevani-residential-premium-farmhouse/ishwer-sevani-residential-premium-farmhouse--photo-11-20220219-172207.webp",
        "alt": "Ishwer Sevani Residential Premium Farmhouse - 20220219 172207",
        "label": "20220219 172207",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ishwer-sevani-residential-premium-farmhouse/ishwer-sevani-residential-premium-farmhouse--photo-12-img-20220121-wa0035.webp",
        "alt": "Ishwer Sevani Residential Premium Farmhouse - Img 20220121 Wa0035",
        "label": "Img 20220121 Wa0035",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ishwer-sevani-residential-premium-farmhouse/ishwer-sevani-residential-premium-farmhouse--photo-13-img-20220219-wa0029.webp",
        "alt": "Ishwer Sevani Residential Premium Farmhouse - Img 20220219 Wa0029",
        "label": "Img 20220219 Wa0029",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ishwer-sevani-residential-premium-farmhouse/ishwer-sevani-residential-premium-farmhouse--photo-14-img-20220226-wa0019.webp",
        "alt": "Ishwer Sevani Residential Premium Farmhouse - Img 20220226 Wa0019",
        "label": "Img 20220226 Wa0019",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ishwer-sevani-residential-premium-farmhouse/ishwer-sevani-residential-premium-farmhouse--photo-15-img-20220226-wa0020.webp",
        "alt": "Ishwer Sevani Residential Premium Farmhouse - Img 20220226 Wa0020",
        "label": "Img 20220226 Wa0020",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ishwer-sevani-residential-premium-farmhouse/ishwer-sevani-residential-premium-farmhouse--photo-16-img-20220226-wa0021.webp",
        "alt": "Ishwer Sevani Residential Premium Farmhouse - Img 20220226 Wa0021",
        "label": "Img 20220226 Wa0021",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ishwer-sevani-residential-premium-farmhouse/ishwer-sevani-residential-premium-farmhouse--photo-17-img-20220226-wa0029.webp",
        "alt": "Ishwer Sevani Residential Premium Farmhouse - Img 20220226 Wa0029",
        "label": "Img 20220226 Wa0029",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ishwer-sevani-residential-premium-farmhouse/ishwer-sevani-residential-premium-farmhouse--photo-18-img-20220226-wa0030.webp",
        "alt": "Ishwer Sevani Residential Premium Farmhouse - Img 20220226 Wa0030",
        "label": "Img 20220226 Wa0030",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ishwer-sevani-residential-premium-farmhouse/ishwer-sevani-residential-premium-farmhouse--photo-19-img-20220308-wa0011.webp",
        "alt": "Ishwer Sevani Residential Premium Farmhouse - Img 20220308 Wa0011",
        "label": "Img 20220308 Wa0011",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ishwer-sevani-residential-premium-farmhouse/ishwer-sevani-residential-premium-farmhouse--photo-20-img-20220308-wa0015.webp",
        "alt": "Ishwer Sevani Residential Premium Farmhouse - Img 20220308 Wa0015",
        "label": "Img 20220308 Wa0015",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ishwer-sevani-residential-premium-farmhouse/ishwer-sevani-residential-premium-farmhouse--photo-21-img-20220308-wa0017.webp",
        "alt": "Ishwer Sevani Residential Premium Farmhouse - Img 20220308 Wa0017",
        "label": "Img 20220308 Wa0017",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ishwer-sevani-residential-premium-farmhouse/ishwer-sevani-residential-premium-farmhouse--photo-22-img-20220318-wa0011.webp",
        "alt": "Ishwer Sevani Residential Premium Farmhouse - Img 20220318 Wa0011",
        "label": "Img 20220318 Wa0011",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ishwer-sevani-residential-premium-farmhouse/ishwer-sevani-residential-premium-farmhouse--photo-23-img-20220318-wa0029.webp",
        "alt": "Ishwer Sevani Residential Premium Farmhouse - Img 20220318 Wa0029",
        "label": "Img 20220318 Wa0029",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ishwer-sevani-residential-premium-farmhouse/ishwer-sevani-residential-premium-farmhouse--photo-24-img-20220322-wa0017.webp",
        "alt": "Ishwer Sevani Residential Premium Farmhouse - Img 20220322 Wa0017",
        "label": "Img 20220322 Wa0017",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ishwer-sevani-residential-premium-farmhouse/ishwer-sevani-residential-premium-farmhouse--photo-25-img-20220322-wa0020.webp",
        "alt": "Ishwer Sevani Residential Premium Farmhouse - Img 20220322 Wa0020",
        "label": "Img 20220322 Wa0020",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ishwer-sevani-residential-premium-farmhouse/ishwer-sevani-residential-premium-farmhouse--photo-26-img-20220403-wa0032.webp",
        "alt": "Ishwer Sevani Residential Premium Farmhouse - Img 20220403 Wa0032",
        "label": "Img 20220403 Wa0032",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ishwer-sevani-residential-premium-farmhouse/ishwer-sevani-residential-premium-farmhouse--photo-27-img-20220403-wa0037.webp",
        "alt": "Ishwer Sevani Residential Premium Farmhouse - Img 20220403 Wa0037",
        "label": "Img 20220403 Wa0037",
        "kind": "photo"
      }
    ]
  },
  {
    "slug": "jayant-patil-yspm-college",
    "title": "Jayant Patil YSPM College",
    "category": "Institutional Construction",
    "location": "Kodoli",
    "status": "Completed",
    "description": "Institutional construction work by JVS Enterprises in Kodoli, focused on durable structure and practical daily use.",
    "scope": [
      "Institutional Building",
      "Civil Construction",
      "RCC Work",
      "Site Supervision"
    ],
    "overview": "Jayant Patil YSPM College is presented through real project imagery, drawings, and on-site progress records maintained by JVS Enterprises.",
    "priorities": [
      "Reliable RCC and structural execution",
      "Daily-use movement planning",
      "Quality supervision across stages",
      "Durable handover standards"
    ],
    "media": [
      {
        "src": "/images/projects/jayant-patil-yspm-college/jayant-patil-yspm-college--pdf-preview-01-1-ground-floor-plan-for-layout.webp",
        "alt": "Jayant Patil YSPM College - 1 Ground Floor Plan For Layout",
        "label": "1 Ground Floor Plan For Layout",
        "kind": "pdf-preview"
      },
      {
        "src": "/images/projects/jayant-patil-yspm-college/jayant-patil-yspm-college--pdf-preview-02-2-first-floor-plan-for-layout.webp",
        "alt": "Jayant Patil YSPM College - 2 First Floor Plan For Layout",
        "label": "2 First Floor Plan For Layout",
        "kind": "pdf-preview"
      }
    ]
  },
  {
    "slug": "kallani",
    "title": "Kallani",
    "category": "Residential Construction",
    "location": "Kolhapur Region",
    "status": "Completed",
    "description": "Kallani is a residential construction project by JVS Enterprises in Kolhapur Region, executed with practical site supervision and durable construction quality.",
    "scope": [
      "Residential Construction",
      "RCC & Structural Work",
      "Finishing",
      "Site Coordination"
    ],
    "overview": "Kallani is presented through real project imagery, drawings, and on-site progress records maintained by JVS Enterprises.",
    "priorities": [
      "Disciplined residential execution",
      "Structural reliability",
      "Finishing and usability focus",
      "Site-level coordination"
    ],
    "media": [
      {
        "src": "/images/projects/kallani/kallani--photo-01-img-20210530-wa0032.webp",
        "alt": "Kallani - Img 20210530 Wa0032",
        "label": "Img 20210530 Wa0032",
        "kind": "photo"
      },
      {
        "src": "/images/projects/kallani/kallani--photo-02-img-20210530-wa0033.webp",
        "alt": "Kallani - Img 20210530 Wa0033",
        "label": "Img 20210530 Wa0033",
        "kind": "photo"
      },
      {
        "src": "/images/projects/kallani/kallani--photo-03-img-20210530-wa0034.webp",
        "alt": "Kallani - Img 20210530 Wa0034",
        "label": "Img 20210530 Wa0034",
        "kind": "photo"
      },
      {
        "src": "/images/projects/kallani/kallani--photo-04-img-20210530-wa0035.webp",
        "alt": "Kallani - Img 20210530 Wa0035",
        "label": "Img 20210530 Wa0035",
        "kind": "photo"
      },
      {
        "src": "/images/projects/kallani/kallani--photo-05-img-20210530-wa0036.webp",
        "alt": "Kallani - Img 20210530 Wa0036",
        "label": "Img 20210530 Wa0036",
        "kind": "photo"
      },
      {
        "src": "/images/projects/kallani/kallani--photo-06-img-20210530-wa0037.webp",
        "alt": "Kallani - Img 20210530 Wa0037",
        "label": "Img 20210530 Wa0037",
        "kind": "photo"
      },
      {
        "src": "/images/projects/kallani/kallani--photo-07-img-20210530-wa0038.webp",
        "alt": "Kallani - Img 20210530 Wa0038",
        "label": "Img 20210530 Wa0038",
        "kind": "photo"
      },
      {
        "src": "/images/projects/kallani/kallani--photo-08-img-20210530-wa0039.webp",
        "alt": "Kallani - Img 20210530 Wa0039",
        "label": "Img 20210530 Wa0039",
        "kind": "photo"
      },
      {
        "src": "/images/projects/kallani/kallani--photo-09-img-20210530-wa0040.webp",
        "alt": "Kallani - Img 20210530 Wa0040",
        "label": "Img 20210530 Wa0040",
        "kind": "photo"
      },
      {
        "src": "/images/projects/kallani/kallani--photo-10-img-20210530-wa0041.webp",
        "alt": "Kallani - Img 20210530 Wa0041",
        "label": "Img 20210530 Wa0041",
        "kind": "photo"
      },
      {
        "src": "/images/projects/kallani/kallani--photo-11-img-20210530-wa0042.webp",
        "alt": "Kallani - Img 20210530 Wa0042",
        "label": "Img 20210530 Wa0042",
        "kind": "photo"
      },
      {
        "src": "/images/projects/kallani/kallani--photo-12-img-20210530-wa0043.webp",
        "alt": "Kallani - Img 20210530 Wa0043",
        "label": "Img 20210530 Wa0043",
        "kind": "photo"
      },
      {
        "src": "/images/projects/kallani/kallani--photo-13-img-20210530-wa0044.webp",
        "alt": "Kallani - Img 20210530 Wa0044",
        "label": "Img 20210530 Wa0044",
        "kind": "photo"
      },
      {
        "src": "/images/projects/kallani/kallani--photo-14-img-20210530-wa0045.webp",
        "alt": "Kallani - Img 20210530 Wa0045",
        "label": "Img 20210530 Wa0045",
        "kind": "photo"
      },
      {
        "src": "/images/projects/kallani/kallani--photo-15-img-20210530-wa0046.webp",
        "alt": "Kallani - Img 20210530 Wa0046",
        "label": "Img 20210530 Wa0046",
        "kind": "photo"
      },
      {
        "src": "/images/projects/kallani/kallani--photo-16-img-20210530-wa0047.webp",
        "alt": "Kallani - Img 20210530 Wa0047",
        "label": "Img 20210530 Wa0047",
        "kind": "photo"
      }
    ]
  },
  {
    "slug": "panhala-farmhouse-premium",
    "title": "Panhala Farmhouse Premium",
    "category": "Farmhouse Construction",
    "location": "Panhala",
    "status": "Completed",
    "description": "Farmhouse construction work by JVS Enterprises in Panhala, covering structural execution, external development, and long-term performance.",
    "scope": [
      "Farmhouse Construction",
      "RCC & Structural Work",
      "Finishing",
      "External Development"
    ],
    "overview": "Panhala Farmhouse Premium is presented through real project imagery, drawings, and on-site progress records maintained by JVS Enterprises.",
    "priorities": [
      "Terrain-aware execution",
      "Drainage and external usability",
      "Long-term weather resilience",
      "Coordinated finishing quality"
    ],
    "media": [
      {
        "src": "/images/projects/panhala-farmhouse-premium/panhala-farmhouse-premium--photo-01-complete-1.webp",
        "alt": "Panhala Farmhouse Premium - Complete 1",
        "label": "Complete 1",
        "kind": "photo"
      },
      {
        "src": "/images/projects/panhala-farmhouse-premium/panhala-farmhouse-premium--photo-02-complete-2.webp",
        "alt": "Panhala Farmhouse Premium - Complete 2",
        "label": "Complete 2",
        "kind": "photo"
      },
      {
        "src": "/images/projects/panhala-farmhouse-premium/panhala-farmhouse-premium--photo-03-20201003-144433.webp",
        "alt": "Panhala Farmhouse Premium - 20201003 144433",
        "label": "20201003 144433",
        "kind": "photo"
      },
      {
        "src": "/images/projects/panhala-farmhouse-premium/panhala-farmhouse-premium--photo-04-20210205-131009.webp",
        "alt": "Panhala Farmhouse Premium - 20210205 131009",
        "label": "20210205 131009",
        "kind": "photo"
      },
      {
        "src": "/images/projects/panhala-farmhouse-premium/panhala-farmhouse-premium--photo-05-20210329-084501.webp",
        "alt": "Panhala Farmhouse Premium - 20210329 084501",
        "label": "20210329 084501",
        "kind": "photo"
      },
      {
        "src": "/images/projects/panhala-farmhouse-premium/panhala-farmhouse-premium--photo-06-20210614-184837.webp",
        "alt": "Panhala Farmhouse Premium - 20210614 184837",
        "label": "20210614 184837",
        "kind": "photo"
      },
      {
        "src": "/images/projects/panhala-farmhouse-premium/panhala-farmhouse-premium--photo-07-20210615-103508.webp",
        "alt": "Panhala Farmhouse Premium - 20210615 103508",
        "label": "20210615 103508",
        "kind": "photo"
      },
      {
        "src": "/images/projects/panhala-farmhouse-premium/panhala-farmhouse-premium--photo-08-20210708-154245.webp",
        "alt": "Panhala Farmhouse Premium - 20210708 154245",
        "label": "20210708 154245",
        "kind": "photo"
      },
      {
        "src": "/images/projects/panhala-farmhouse-premium/panhala-farmhouse-premium--photo-09-20210708-154324.webp",
        "alt": "Panhala Farmhouse Premium - 20210708 154324",
        "label": "20210708 154324",
        "kind": "photo"
      },
      {
        "src": "/images/projects/panhala-farmhouse-premium/panhala-farmhouse-premium--photo-10-20220311-150830.webp",
        "alt": "Panhala Farmhouse Premium - 20220311 150830",
        "label": "20220311 150830",
        "kind": "photo"
      },
      {
        "src": "/images/projects/panhala-farmhouse-premium/panhala-farmhouse-premium--photo-11-20220316-120709.webp",
        "alt": "Panhala Farmhouse Premium - 20220316 120709",
        "label": "20220316 120709",
        "kind": "photo"
      },
      {
        "src": "/images/projects/panhala-farmhouse-premium/panhala-farmhouse-premium--photo-12-20220521-132650.webp",
        "alt": "Panhala Farmhouse Premium - 20220521 132650",
        "label": "20220521 132650",
        "kind": "photo"
      },
      {
        "src": "/images/projects/panhala-farmhouse-premium/panhala-farmhouse-premium--photo-13-20220526-174430.webp",
        "alt": "Panhala Farmhouse Premium - 20220526 174430",
        "label": "20220526 174430",
        "kind": "photo"
      },
      {
        "src": "/images/projects/panhala-farmhouse-premium/panhala-farmhouse-premium--photo-14-20220602-122124.webp",
        "alt": "Panhala Farmhouse Premium - 20220602 122124",
        "label": "20220602 122124",
        "kind": "photo"
      },
      {
        "src": "/images/projects/panhala-farmhouse-premium/panhala-farmhouse-premium--photo-15-20220613-112403.webp",
        "alt": "Panhala Farmhouse Premium - 20220613 112403",
        "label": "20220613 112403",
        "kind": "photo"
      },
      {
        "src": "/images/projects/panhala-farmhouse-premium/panhala-farmhouse-premium--photo-16-img-20200626-wa0017.webp",
        "alt": "Panhala Farmhouse Premium - Img 20200626 Wa0017",
        "label": "Img 20200626 Wa0017",
        "kind": "photo"
      },
      {
        "src": "/images/projects/panhala-farmhouse-premium/panhala-farmhouse-premium--photo-17-img-20201013-wa0043.webp",
        "alt": "Panhala Farmhouse Premium - Img 20201013 Wa0043",
        "label": "Img 20201013 Wa0043",
        "kind": "photo"
      },
      {
        "src": "/images/projects/panhala-farmhouse-premium/panhala-farmhouse-premium--photo-18-img-20201119-wa0006.webp",
        "alt": "Panhala Farmhouse Premium - Img 20201119 Wa0006",
        "label": "Img 20201119 Wa0006",
        "kind": "photo"
      },
      {
        "src": "/images/projects/panhala-farmhouse-premium/panhala-farmhouse-premium--photo-19-img-20201119-wa0007.webp",
        "alt": "Panhala Farmhouse Premium - Img 20201119 Wa0007",
        "label": "Img 20201119 Wa0007",
        "kind": "photo"
      },
      {
        "src": "/images/projects/panhala-farmhouse-premium/panhala-farmhouse-premium--photo-20-img-20201119-wa0039.webp",
        "alt": "Panhala Farmhouse Premium - Img 20201119 Wa0039",
        "label": "Img 20201119 Wa0039",
        "kind": "photo"
      },
      {
        "src": "/images/projects/panhala-farmhouse-premium/panhala-farmhouse-premium--photo-21-img-20201207-wa0031.webp",
        "alt": "Panhala Farmhouse Premium - Img 20201207 Wa0031",
        "label": "Img 20201207 Wa0031",
        "kind": "photo"
      },
      {
        "src": "/images/projects/panhala-farmhouse-premium/panhala-farmhouse-premium--photo-22-img-20210104-wa0011.webp",
        "alt": "Panhala Farmhouse Premium - Img 20210104 Wa0011",
        "label": "Img 20210104 Wa0011",
        "kind": "photo"
      },
      {
        "src": "/images/projects/panhala-farmhouse-premium/panhala-farmhouse-premium--photo-23-img-20210725-wa0021.webp",
        "alt": "Panhala Farmhouse Premium - Img 20210725 Wa0021",
        "label": "Img 20210725 Wa0021",
        "kind": "photo"
      },
      {
        "src": "/images/projects/panhala-farmhouse-premium/panhala-farmhouse-premium--photo-24-img-20220304-wa0009.webp",
        "alt": "Panhala Farmhouse Premium - Img 20220304 Wa0009",
        "label": "Img 20220304 Wa0009",
        "kind": "photo"
      },
      {
        "src": "/images/projects/panhala-farmhouse-premium/panhala-farmhouse-premium--photo-25-img-20220405-wa0051.webp",
        "alt": "Panhala Farmhouse Premium - Img 20220405 Wa0051",
        "label": "Img 20220405 Wa0051",
        "kind": "photo"
      },
      {
        "src": "/images/projects/panhala-farmhouse-premium/panhala-farmhouse-premium--photo-26-img-20221003-wa0003.webp",
        "alt": "Panhala Farmhouse Premium - Img 20221003 Wa0003",
        "label": "Img 20221003 Wa0003",
        "kind": "photo"
      },
      {
        "src": "/images/projects/panhala-farmhouse-premium/panhala-farmhouse-premium--photo-27-img-20221003-wa0004.webp",
        "alt": "Panhala Farmhouse Premium - Img 20221003 Wa0004",
        "label": "Img 20221003 Wa0004",
        "kind": "photo"
      },
      {
        "src": "/images/projects/panhala-farmhouse-premium/panhala-farmhouse-premium--photo-28-img-20221003-wa0005.webp",
        "alt": "Panhala Farmhouse Premium - Img 20221003 Wa0005",
        "label": "Img 20221003 Wa0005",
        "kind": "photo"
      },
      {
        "src": "/images/projects/panhala-farmhouse-premium/panhala-farmhouse-premium--photo-29-img-20221003-wa0008.webp",
        "alt": "Panhala Farmhouse Premium - Img 20221003 Wa0008",
        "label": "Img 20221003 Wa0008",
        "kind": "photo"
      },
      {
        "src": "/images/projects/panhala-farmhouse-premium/panhala-farmhouse-premium--photo-30-img-20221003-wa0014.webp",
        "alt": "Panhala Farmhouse Premium - Img 20221003 Wa0014",
        "label": "Img 20221003 Wa0014",
        "kind": "photo"
      }
    ]
  },
  {
    "slug": "ranjeet-shah",
    "title": "Ranjeet Shah",
    "category": "Residential Construction",
    "location": "Kolhapur Region",
    "status": "Completed",
    "description": "Ranjeet Shah is a residential construction project by JVS Enterprises in Kolhapur Region, executed with practical site supervision and durable construction quality.",
    "scope": [
      "Residential Construction",
      "RCC & Structural Work",
      "Finishing",
      "Site Coordination"
    ],
    "overview": "Ranjeet Shah is presented through real project imagery, drawings, and on-site progress records maintained by JVS Enterprises.",
    "priorities": [
      "Disciplined residential execution",
      "Structural reliability",
      "Finishing and usability focus",
      "Site-level coordination"
    ],
    "media": [
      {
        "src": "/images/projects/ranjeet-shah/ranjeet-shah--photo-01-complete-1.webp",
        "alt": "Ranjeet Shah - Complete 1",
        "label": "Complete 1",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ranjeet-shah/ranjeet-shah--photo-02-20171225-053117.webp",
        "alt": "Ranjeet Shah - 20171225 053117",
        "label": "20171225 053117",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ranjeet-shah/ranjeet-shah--photo-03-20181025-162129.webp",
        "alt": "Ranjeet Shah - 20181025 162129",
        "label": "20181025 162129",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ranjeet-shah/ranjeet-shah--photo-04-20181103-173221.webp",
        "alt": "Ranjeet Shah - 20181103 173221",
        "label": "20181103 173221",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ranjeet-shah/ranjeet-shah--photo-05-img-20181019-wa0046.webp",
        "alt": "Ranjeet Shah - Img 20181019 Wa0046",
        "label": "Img 20181019 Wa0046",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ranjeet-shah/ranjeet-shah--photo-06-img-20181220-wa0018.webp",
        "alt": "Ranjeet Shah - Img 20181220 Wa0018",
        "label": "Img 20181220 Wa0018",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ranjeet-shah/ranjeet-shah--photo-07-img-20181220-wa0019.webp",
        "alt": "Ranjeet Shah - Img 20181220 Wa0019",
        "label": "Img 20181220 Wa0019",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ranjeet-shah/ranjeet-shah--photo-08-img-20181220-wa0031.webp",
        "alt": "Ranjeet Shah - Img 20181220 Wa0031",
        "label": "Img 20181220 Wa0031",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ranjeet-shah/ranjeet-shah--photo-09-img-20181220-wa0032.webp",
        "alt": "Ranjeet Shah - Img 20181220 Wa0032",
        "label": "Img 20181220 Wa0032",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ranjeet-shah/ranjeet-shah--photo-10-img-20181220-wa0035.webp",
        "alt": "Ranjeet Shah - Img 20181220 Wa0035",
        "label": "Img 20181220 Wa0035",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ranjeet-shah/ranjeet-shah--photo-11-img-20181220-wa0038.webp",
        "alt": "Ranjeet Shah - Img 20181220 Wa0038",
        "label": "Img 20181220 Wa0038",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ranjeet-shah/ranjeet-shah--photo-12-img-20181223-wa0027.webp",
        "alt": "Ranjeet Shah - Img 20181223 Wa0027",
        "label": "Img 20181223 Wa0027",
        "kind": "photo"
      },
      {
        "src": "/images/projects/ranjeet-shah/ranjeet-shah--photo-13-img-20181228-wa0019.webp",
        "alt": "Ranjeet Shah - Img 20181228 Wa0019",
        "label": "Img 20181228 Wa0019",
        "kind": "photo"
      }
    ]
  },
  {
    "slug": "sanjay-benadekar-residential-panhala",
    "title": "Sanjay Benadekar Residential Panhala",
    "category": "Residential Construction",
    "location": "Panhala",
    "status": "Completed",
    "description": "Sanjay Benadekar Residential Panhala is a residential construction project by JVS Enterprises in Panhala, executed with practical site supervision and durable construction quality.",
    "scope": [
      "Residential Construction",
      "RCC & Structural Work",
      "Finishing",
      "Site Coordination"
    ],
    "overview": "Sanjay Benadekar Residential Panhala is presented through real project imagery, drawings, and on-site progress records maintained by JVS Enterprises.",
    "priorities": [
      "Disciplined residential execution",
      "Structural reliability",
      "Finishing and usability focus",
      "Site-level coordination"
    ],
    "media": [
      {
        "src": "/images/projects/sanjay-benadekar-residential-panhala/sanjay-benadekar-residential-panhala--photo-01-completed-1.webp",
        "alt": "Sanjay Benadekar Residential Panhala - Completed 1",
        "label": "Completed 1",
        "kind": "photo"
      },
      {
        "src": "/images/projects/sanjay-benadekar-residential-panhala/sanjay-benadekar-residential-panhala--photo-02-20190421-125702.webp",
        "alt": "Sanjay Benadekar Residential Panhala - 20190421 125702",
        "label": "20190421 125702",
        "kind": "photo"
      },
      {
        "src": "/images/projects/sanjay-benadekar-residential-panhala/sanjay-benadekar-residential-panhala--photo-03-20190421-150121.webp",
        "alt": "Sanjay Benadekar Residential Panhala - 20190421 150121",
        "label": "20190421 150121",
        "kind": "photo"
      },
      {
        "src": "/images/projects/sanjay-benadekar-residential-panhala/sanjay-benadekar-residential-panhala--photo-04-20190429-174003.webp",
        "alt": "Sanjay Benadekar Residential Panhala - 20190429 174003",
        "label": "20190429 174003",
        "kind": "photo"
      }
    ]
  },
  {
    "slug": "site-work",
    "title": "Site Work",
    "category": "Site Development",
    "location": "Kolhapur Region",
    "status": "Completed",
    "description": "Site development work by JVS Enterprises in Kolhapur Region, including ground-level execution, drainage considerations, and external usability.",
    "scope": [
      "Site Development",
      "Ground Work",
      "Drainage Coordination",
      "Execution Supervision"
    ],
    "overview": "Site Work is presented through real project imagery, drawings, and on-site progress records maintained by JVS Enterprises.",
    "priorities": [
      "Practical ground-level sequencing",
      "Drainage and water movement control",
      "Usable external circulation",
      "Long-term maintenance awareness"
    ],
    "media": [
      {
        "src": "/images/projects/site-work/site-work--photo-01-20170227-131150.webp",
        "alt": "Site Work - 20170227 131150",
        "label": "20170227 131150",
        "kind": "photo"
      },
      {
        "src": "/images/projects/site-work/site-work--photo-02-20170227-131514.webp",
        "alt": "Site Work - 20170227 131514",
        "label": "20170227 131514",
        "kind": "photo"
      },
      {
        "src": "/images/projects/site-work/site-work--photo-03-20170227-131521.webp",
        "alt": "Site Work - 20170227 131521",
        "label": "20170227 131521",
        "kind": "photo"
      },
      {
        "src": "/images/projects/site-work/site-work--photo-04-20170315-171414.webp",
        "alt": "Site Work - 20170315 171414",
        "label": "20170315 171414",
        "kind": "photo"
      },
      {
        "src": "/images/projects/site-work/site-work--photo-05-20170315-171637.webp",
        "alt": "Site Work - 20170315 171637",
        "label": "20170315 171637",
        "kind": "photo"
      },
      {
        "src": "/images/projects/site-work/site-work--photo-06-20170507-131044.webp",
        "alt": "Site Work - 20170507 131044",
        "label": "20170507 131044",
        "kind": "photo"
      }
    ]
  },
  {
    "slug": "sunil-kulkarni-residential-five-row-houses",
    "title": "Sunil Kulkarni Residential Five Row Houses",
    "category": "Residential Construction",
    "location": "Kolhapur Region",
    "status": "Completed",
    "description": "Sunil Kulkarni Residential Five Row Houses is a residential construction project by JVS Enterprises in Kolhapur Region, executed with practical site supervision and durable construction quality.",
    "scope": [
      "Residential Construction",
      "RCC & Structural Work",
      "Finishing",
      "Site Coordination"
    ],
    "overview": "Sunil Kulkarni Residential Five Row Houses is presented through real project imagery, drawings, and on-site progress records maintained by JVS Enterprises.",
    "priorities": [
      "Disciplined residential execution",
      "Structural reliability",
      "Finishing and usability focus",
      "Site-level coordination"
    ],
    "media": [
      {
        "src": "/images/projects/sunil-kulkarni-residential-five-row-houses/sunil-kulkarni-residential-five-row-houses--photo-01-complete.webp",
        "alt": "Sunil Kulkarni Residential Five Row Houses - Complete",
        "label": "Complete",
        "kind": "photo"
      },
      {
        "src": "/images/projects/sunil-kulkarni-residential-five-row-houses/sunil-kulkarni-residential-five-row-houses--photo-02-20180910-163436.webp",
        "alt": "Sunil Kulkarni Residential Five Row Houses - 20180910 163436",
        "label": "20180910 163436",
        "kind": "photo"
      },
      {
        "src": "/images/projects/sunil-kulkarni-residential-five-row-houses/sunil-kulkarni-residential-five-row-houses--photo-03-20190302-144243.webp",
        "alt": "Sunil Kulkarni Residential Five Row Houses - 20190302 144243",
        "label": "20190302 144243",
        "kind": "photo"
      },
      {
        "src": "/images/projects/sunil-kulkarni-residential-five-row-houses/sunil-kulkarni-residential-five-row-houses--photo-04-20190702-151135.webp",
        "alt": "Sunil Kulkarni Residential Five Row Houses - 20190702 151135",
        "label": "20190702 151135",
        "kind": "photo"
      },
      {
        "src": "/images/projects/sunil-kulkarni-residential-five-row-houses/sunil-kulkarni-residential-five-row-houses--photo-05-20191109-170102.webp",
        "alt": "Sunil Kulkarni Residential Five Row Houses - 20191109 170102",
        "label": "20191109 170102",
        "kind": "photo"
      },
      {
        "src": "/images/projects/sunil-kulkarni-residential-five-row-houses/sunil-kulkarni-residential-five-row-houses--photo-06-20200119-143308.webp",
        "alt": "Sunil Kulkarni Residential Five Row Houses - 20200119 143308",
        "label": "20200119 143308",
        "kind": "photo"
      },
      {
        "src": "/images/projects/sunil-kulkarni-residential-five-row-houses/sunil-kulkarni-residential-five-row-houses--photo-07-20200119-144523.webp",
        "alt": "Sunil Kulkarni Residential Five Row Houses - 20200119 144523",
        "label": "20200119 144523",
        "kind": "photo"
      },
      {
        "src": "/images/projects/sunil-kulkarni-residential-five-row-houses/sunil-kulkarni-residential-five-row-houses--photo-08-20200119-144743-001.webp",
        "alt": "Sunil Kulkarni Residential Five Row Houses - 20200119 144743 001",
        "label": "20200119 144743 001",
        "kind": "photo"
      },
      {
        "src": "/images/projects/sunil-kulkarni-residential-five-row-houses/sunil-kulkarni-residential-five-row-houses--photo-09-20200119-144903.webp",
        "alt": "Sunil Kulkarni Residential Five Row Houses - 20200119 144903",
        "label": "20200119 144903",
        "kind": "photo"
      },
      {
        "src": "/images/projects/sunil-kulkarni-residential-five-row-houses/sunil-kulkarni-residential-five-row-houses--photo-10-20200119-145209.webp",
        "alt": "Sunil Kulkarni Residential Five Row Houses - 20200119 145209",
        "label": "20200119 145209",
        "kind": "photo"
      },
      {
        "src": "/images/projects/sunil-kulkarni-residential-five-row-houses/sunil-kulkarni-residential-five-row-houses--photo-11-20200119-145229.webp",
        "alt": "Sunil Kulkarni Residential Five Row Houses - 20200119 145229",
        "label": "20200119 145229",
        "kind": "photo"
      },
      {
        "src": "/images/projects/sunil-kulkarni-residential-five-row-houses/sunil-kulkarni-residential-five-row-houses--photo-12-20200613-160335.webp",
        "alt": "Sunil Kulkarni Residential Five Row Houses - 20200613 160335",
        "label": "20200613 160335",
        "kind": "photo"
      },
      {
        "src": "/images/projects/sunil-kulkarni-residential-five-row-houses/sunil-kulkarni-residential-five-row-houses--photo-13-20200903-123457.webp",
        "alt": "Sunil Kulkarni Residential Five Row Houses - 20200903 123457",
        "label": "20200903 123457",
        "kind": "photo"
      },
      {
        "src": "/images/projects/sunil-kulkarni-residential-five-row-houses/sunil-kulkarni-residential-five-row-houses--photo-14-20200912-134926.webp",
        "alt": "Sunil Kulkarni Residential Five Row Houses - 20200912 134926",
        "label": "20200912 134926",
        "kind": "photo"
      },
      {
        "src": "/images/projects/sunil-kulkarni-residential-five-row-houses/sunil-kulkarni-residential-five-row-houses--photo-15-img-20180607-wa0119.webp",
        "alt": "Sunil Kulkarni Residential Five Row Houses - Img 20180607 Wa0119",
        "label": "Img 20180607 Wa0119",
        "kind": "photo"
      },
      {
        "src": "/images/projects/sunil-kulkarni-residential-five-row-houses/sunil-kulkarni-residential-five-row-houses--photo-16-img-20180902-wa0002.webp",
        "alt": "Sunil Kulkarni Residential Five Row Houses - Img 20180902 Wa0002",
        "label": "Img 20180902 Wa0002",
        "kind": "photo"
      },
      {
        "src": "/images/projects/sunil-kulkarni-residential-five-row-houses/sunil-kulkarni-residential-five-row-houses--photo-17-img-20200610-wa0031.webp",
        "alt": "Sunil Kulkarni Residential Five Row Houses - Img 20200610 Wa0031",
        "label": "Img 20200610 Wa0031",
        "kind": "photo"
      },
      {
        "src": "/images/projects/sunil-kulkarni-residential-five-row-houses/sunil-kulkarni-residential-five-row-houses--photo-18-img-20200630-wa0025.webp",
        "alt": "Sunil Kulkarni Residential Five Row Houses - Img 20200630 Wa0025",
        "label": "Img 20200630 Wa0025",
        "kind": "photo"
      },
      {
        "src": "/images/projects/sunil-kulkarni-residential-five-row-houses/sunil-kulkarni-residential-five-row-houses--photo-19-img-20200828-wa0020.webp",
        "alt": "Sunil Kulkarni Residential Five Row Houses - Img 20200828 Wa0020",
        "label": "Img 20200828 Wa0020",
        "kind": "photo"
      },
      {
        "src": "/images/projects/sunil-kulkarni-residential-five-row-houses/sunil-kulkarni-residential-five-row-houses--photo-20-img-20200911-wa0024.webp",
        "alt": "Sunil Kulkarni Residential Five Row Houses - Img 20200911 Wa0024",
        "label": "Img 20200911 Wa0024",
        "kind": "photo"
      },
      {
        "src": "/images/projects/sunil-kulkarni-residential-five-row-houses/sunil-kulkarni-residential-five-row-houses--photo-21-img-20200911-wa0026.webp",
        "alt": "Sunil Kulkarni Residential Five Row Houses - Img 20200911 Wa0026",
        "label": "Img 20200911 Wa0026",
        "kind": "photo"
      },
      {
        "src": "/images/projects/sunil-kulkarni-residential-five-row-houses/sunil-kulkarni-residential-five-row-houses--photo-22-img-20200921-wa0025.webp",
        "alt": "Sunil Kulkarni Residential Five Row Houses - Img 20200921 Wa0025",
        "label": "Img 20200921 Wa0025",
        "kind": "photo"
      },
      {
        "src": "/images/projects/sunil-kulkarni-residential-five-row-houses/sunil-kulkarni-residential-five-row-houses--photo-23-img-20200921-wa0027.webp",
        "alt": "Sunil Kulkarni Residential Five Row Houses - Img 20200921 Wa0027",
        "label": "Img 20200921 Wa0027",
        "kind": "photo"
      },
      {
        "src": "/images/projects/sunil-kulkarni-residential-five-row-houses/sunil-kulkarni-residential-five-row-houses--photo-24-img-20210129-wa0036.webp",
        "alt": "Sunil Kulkarni Residential Five Row Houses - Img 20210129 Wa0036",
        "label": "Img 20210129 Wa0036",
        "kind": "photo"
      },
      {
        "src": "/images/projects/sunil-kulkarni-residential-five-row-houses/sunil-kulkarni-residential-five-row-houses--drawing-25-drawing-1.webp",
        "alt": "Sunil Kulkarni Residential Five Row Houses - Drawing 1",
        "label": "Drawing 1",
        "kind": "drawing"
      },
      {
        "src": "/images/projects/sunil-kulkarni-residential-five-row-houses/sunil-kulkarni-residential-five-row-houses--drawing-26-drawing-2.webp",
        "alt": "Sunil Kulkarni Residential Five Row Houses - Drawing 2",
        "label": "Drawing 2",
        "kind": "drawing"
      },
      {
        "src": "/images/projects/sunil-kulkarni-residential-five-row-houses/sunil-kulkarni-residential-five-row-houses--drawing-27-drawing-3.webp",
        "alt": "Sunil Kulkarni Residential Five Row Houses - Drawing 3",
        "label": "Drawing 3",
        "kind": "drawing"
      },
      {
        "src": "/images/projects/sunil-kulkarni-residential-five-row-houses/sunil-kulkarni-residential-five-row-houses--drawing-28-drawing-4.webp",
        "alt": "Sunil Kulkarni Residential Five Row Houses - Drawing 4",
        "label": "Drawing 4",
        "kind": "drawing"
      }
    ]
  },
  {
    "slug": "vinayak-goliwadkar-residential-house",
    "title": "Vinayak Goliwadkar Residential House",
    "category": "Residential Construction",
    "location": "Kolhapur Region",
    "status": "Completed",
    "description": "Vinayak Goliwadkar Residential House is a residential construction project by JVS Enterprises in Kolhapur Region, executed with practical site supervision and durable construction quality.",
    "scope": [
      "Residential Construction",
      "RCC & Structural Work",
      "Finishing",
      "Site Coordination"
    ],
    "overview": "Vinayak Goliwadkar Residential House is presented through real project imagery, drawings, and on-site progress records maintained by JVS Enterprises.",
    "priorities": [
      "Disciplined residential execution",
      "Structural reliability",
      "Finishing and usability focus",
      "Site-level coordination"
    ],
    "media": [
      {
        "src": "/images/projects/vinayak-goliwadkar-residential-house/vinayak-goliwadkar-residential-house--photo-01-complete-1.webp",
        "alt": "Vinayak Goliwadkar Residential House - Complete 1",
        "label": "Complete 1",
        "kind": "photo"
      },
      {
        "src": "/images/projects/vinayak-goliwadkar-residential-house/vinayak-goliwadkar-residential-house--photo-02-complete-2.webp",
        "alt": "Vinayak Goliwadkar Residential House - Complete 2",
        "label": "Complete 2",
        "kind": "photo"
      },
      {
        "src": "/images/projects/vinayak-goliwadkar-residential-house/vinayak-goliwadkar-residential-house--photo-03-complete-3.webp",
        "alt": "Vinayak Goliwadkar Residential House - Complete 3",
        "label": "Complete 3",
        "kind": "photo"
      },
      {
        "src": "/images/projects/vinayak-goliwadkar-residential-house/vinayak-goliwadkar-residential-house--photo-04-20200717-162104.webp",
        "alt": "Vinayak Goliwadkar Residential House - 20200717 162104",
        "label": "20200717 162104",
        "kind": "photo"
      },
      {
        "src": "/images/projects/vinayak-goliwadkar-residential-house/vinayak-goliwadkar-residential-house--photo-05-20200827-132259.webp",
        "alt": "Vinayak Goliwadkar Residential House - 20200827 132259",
        "label": "20200827 132259",
        "kind": "photo"
      },
      {
        "src": "/images/projects/vinayak-goliwadkar-residential-house/vinayak-goliwadkar-residential-house--photo-06-20200827-173352.webp",
        "alt": "Vinayak Goliwadkar Residential House - 20200827 173352",
        "label": "20200827 173352",
        "kind": "photo"
      },
      {
        "src": "/images/projects/vinayak-goliwadkar-residential-house/vinayak-goliwadkar-residential-house--photo-07-20200901-095927.webp",
        "alt": "Vinayak Goliwadkar Residential House - 20200901 095927",
        "label": "20200901 095927",
        "kind": "photo"
      },
      {
        "src": "/images/projects/vinayak-goliwadkar-residential-house/vinayak-goliwadkar-residential-house--photo-08-img-20200504-wa0046.webp",
        "alt": "Vinayak Goliwadkar Residential House - Img 20200504 Wa0046",
        "label": "Img 20200504 Wa0046",
        "kind": "photo"
      },
      {
        "src": "/images/projects/vinayak-goliwadkar-residential-house/vinayak-goliwadkar-residential-house--photo-09-img-20200504-wa0056.webp",
        "alt": "Vinayak Goliwadkar Residential House - Img 20200504 Wa0056",
        "label": "Img 20200504 Wa0056",
        "kind": "photo"
      },
      {
        "src": "/images/projects/vinayak-goliwadkar-residential-house/vinayak-goliwadkar-residential-house--photo-10-img-20200504-wa0060.webp",
        "alt": "Vinayak Goliwadkar Residential House - Img 20200504 Wa0060",
        "label": "Img 20200504 Wa0060",
        "kind": "photo"
      },
      {
        "src": "/images/projects/vinayak-goliwadkar-residential-house/vinayak-goliwadkar-residential-house--photo-11-img-20201118-wa0033.webp",
        "alt": "Vinayak Goliwadkar Residential House - Img 20201118 Wa0033",
        "label": "Img 20201118 Wa0033",
        "kind": "photo"
      },
      {
        "src": "/images/projects/vinayak-goliwadkar-residential-house/vinayak-goliwadkar-residential-house--photo-12-img-20201118-wa0034.webp",
        "alt": "Vinayak Goliwadkar Residential House - Img 20201118 Wa0034",
        "label": "Img 20201118 Wa0034",
        "kind": "photo"
      },
      {
        "src": "/images/projects/vinayak-goliwadkar-residential-house/vinayak-goliwadkar-residential-house--photo-13-img-20210305-wa0020.webp",
        "alt": "Vinayak Goliwadkar Residential House - Img 20210305 Wa0020",
        "label": "Img 20210305 Wa0020",
        "kind": "photo"
      },
      {
        "src": "/images/projects/vinayak-goliwadkar-residential-house/vinayak-goliwadkar-residential-house--photo-14-img-20210702-wa0016.webp",
        "alt": "Vinayak Goliwadkar Residential House - Img 20210702 Wa0016",
        "label": "Img 20210702 Wa0016",
        "kind": "photo"
      },
      {
        "src": "/images/projects/vinayak-goliwadkar-residential-house/vinayak-goliwadkar-residential-house--photo-15-img-20210707-wa0049.webp",
        "alt": "Vinayak Goliwadkar Residential House - Img 20210707 Wa0049",
        "label": "Img 20210707 Wa0049",
        "kind": "photo"
      },
      {
        "src": "/images/projects/vinayak-goliwadkar-residential-house/vinayak-goliwadkar-residential-house--photo-16-img-20210709-wa0021.webp",
        "alt": "Vinayak Goliwadkar Residential House - Img 20210709 Wa0021",
        "label": "Img 20210709 Wa0021",
        "kind": "photo"
      },
      {
        "src": "/images/projects/vinayak-goliwadkar-residential-house/vinayak-goliwadkar-residential-house--photo-17-img-20210725-wa0048.webp",
        "alt": "Vinayak Goliwadkar Residential House - Img 20210725 Wa0048",
        "label": "Img 20210725 Wa0048",
        "kind": "photo"
      },
      {
        "src": "/images/projects/vinayak-goliwadkar-residential-house/vinayak-goliwadkar-residential-house--drawing-18-demo-drawing-1.webp",
        "alt": "Vinayak Goliwadkar Residential House - Demo Drawing 1",
        "label": "Demo Drawing 1",
        "kind": "drawing"
      },
      {
        "src": "/images/projects/vinayak-goliwadkar-residential-house/vinayak-goliwadkar-residential-house--drawing-19-demo-drawing-2.webp",
        "alt": "Vinayak Goliwadkar Residential House - Demo Drawing 2",
        "label": "Demo Drawing 2",
        "kind": "drawing"
      },
      {
        "src": "/images/projects/vinayak-goliwadkar-residential-house/vinayak-goliwadkar-residential-house--drawing-20-drawing-1.webp",
        "alt": "Vinayak Goliwadkar Residential House - Drawing 1",
        "label": "Drawing 1",
        "kind": "drawing"
      },
      {
        "src": "/images/projects/vinayak-goliwadkar-residential-house/vinayak-goliwadkar-residential-house--drawing-21-drawing-2.webp",
        "alt": "Vinayak Goliwadkar Residential House - Drawing 2",
        "label": "Drawing 2",
        "kind": "drawing"
      },
      {
        "src": "/images/projects/vinayak-goliwadkar-residential-house/vinayak-goliwadkar-residential-house--drawing-22-map.webp",
        "alt": "Vinayak Goliwadkar Residential House - Map",
        "label": "Map",
        "kind": "drawing"
      }
    ]
  }
];
